/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.pro.software.academico.tela;

import br.pro.software.academico.model.Curso;
import br.pro.software.academico.dao.CursoDAO;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author andyc
 */
public class CursosTela extends javax.swing.JFrame {

    /**
     * Creates new form CursosTela
     */
    public CursosTela() {
        super("Cursos");
        initComponents();
        buscarCursos();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    private void buscarCursos() {
        try {
            recarregarCursos();
            cursosComboBoxActionPerformed(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Cursos indisponíveis, tente novamente mais tarde");
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cursosComboBox = new javax.swing.JComboBox<>();
        idCursoTextField = new javax.swing.JTextField();
        nomeCursoTextField = new javax.swing.JTextField();
        tipoCursoTextField = new javax.swing.JTextField();
        adicionarCursoButton = new javax.swing.JButton();
        atualizarCursoButton = new javax.swing.JButton();
        removerCursoButton = new javax.swing.JButton();
        cancelarCursoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerenciamento de cursos"));

        cursosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursosComboBoxActionPerformed(evt);
            }
        });

        idCursoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("id"));
        idCursoTextField.setEnabled(false);
        idCursoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCursoTextFieldActionPerformed(evt);
            }
        });

        nomeCursoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("nome"));
        nomeCursoTextField.setEnabled(false);
        nomeCursoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCursoTextFieldActionPerformed(evt);
            }
        });

        tipoCursoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("tipo"));
        tipoCursoTextField.setEnabled(false);
        tipoCursoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCursoTextFieldActionPerformed(evt);
            }
        });

        adicionarCursoButton.setText("Novo");
        adicionarCursoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarCursoButtonActionPerformed(evt);
            }
        });

        atualizarCursoButton.setText("Atualizar");
        atualizarCursoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCursoButtonActionPerformed(evt);
            }
        });

        removerCursoButton.setText("Remover");
        removerCursoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerCursoButtonActionPerformed(evt);
            }
        });

        cancelarCursoButton.setText("Cancelar");
        cancelarCursoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCursoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeCursoTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cursosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idCursoTextField)
                            .addComponent(tipoCursoTextField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(removerCursoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(adicionarCursoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atualizarCursoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(cancelarCursoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cursosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(idCursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeCursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoCursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adicionarCursoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(atualizarCursoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removerCursoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(cancelarCursoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoCursoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCursoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoCursoTextFieldActionPerformed

    private void idCursoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCursoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCursoTextFieldActionPerformed

    private void nomeCursoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCursoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCursoTextFieldActionPerformed

    private void adicionarCursoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarCursoButtonActionPerformed
        if (adicionarCursoButton.getText().equals("Novo")) {
            adicionarCursoButton.setText("CONFIRMAR");
            adicionarCursoButton.setBackground(Color.GREEN);
            cancelarCursoButton.setBackground(Color.red);
            nomeCursoTextField.setText("");
            nomeCursoTextField.setEnabled(true);
            tipoCursoTextField.setText("");
            tipoCursoTextField.setEnabled(true);
        } else {
            Curso curso = new Curso(0, nomeCursoTextField.getText(), tipoCursoTextField.getText());
            CursoDAO cursoDAO = new CursoDAO();
            try {
                cursoDAO.cadastrar(curso);
                recarregarCursos();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e);
            }
            desfazer();
        }
        
    }//GEN-LAST:event_adicionarCursoButtonActionPerformed

    private void recarregarCursos() {
        CursoDAO cursoDAO = new CursoDAO();
        try {
            Curso[] cursos = cursoDAO.obterCursos();
            cursosComboBox.setModel(new DefaultComboBoxModel<>(cursos));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void cancelarCursoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCursoButtonActionPerformed
        desfazer();
    }//GEN-LAST:event_cancelarCursoButtonActionPerformed

    private void removerCursoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerCursoButtonActionPerformed
        if (removerCursoButton.getText().equals("Remover")) {
            removerCursoButton.setText("CONFIRMAR");
            removerCursoButton.setBackground(Color.GREEN);
            cancelarCursoButton.setBackground(Color.red);
        } else {
            Curso curso = (Curso)cursosComboBox.getSelectedItem();
            CursoDAO cursoDAO = new CursoDAO();
            try {
                cursoDAO.remover(curso);
                recarregarCursos();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e);
            }
            desfazer();
        }
    }//GEN-LAST:event_removerCursoButtonActionPerformed

    private void cursosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursosComboBoxActionPerformed
           Curso curso = (Curso)cursosComboBox.getSelectedItem();
           idCursoTextField.setText("" + curso.getId());
           nomeCursoTextField.setText(curso.getNome());
           tipoCursoTextField.setText(curso.getTipo());
           
    }//GEN-LAST:event_cursosComboBoxActionPerformed

    private void atualizarCursoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarCursoButtonActionPerformed
        if (atualizarCursoButton.getText().equals("Atualizar")) {
            atualizarCursoButton.setText("CONFIRMAR");
            atualizarCursoButton.setBackground(Color.GREEN);
            cancelarCursoButton.setBackground(Color.red);
            nomeCursoTextField.setEnabled(true);
            tipoCursoTextField.setEnabled(true);
        } else {
            Curso curso = new Curso(Integer.parseInt(idCursoTextField.getText()), nomeCursoTextField.getText(), tipoCursoTextField.getText());
            CursoDAO cursoDAO = new CursoDAO();
            try {
                cursoDAO.atualizar(curso);
                desfazer();
                recarregarCursos();
                cursosComboBoxActionPerformed(null);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_atualizarCursoButtonActionPerformed

    private void desfazer() {
        adicionarCursoButton.setText("Novo");
        adicionarCursoButton.setBackground(Color.LIGHT_GRAY);
        removerCursoButton.setText("Remover");
        removerCursoButton.setBackground(Color.LIGHT_GRAY);
        atualizarCursoButton.setText("Atualizar");
        atualizarCursoButton.setBackground(Color.LIGHT_GRAY);
        nomeCursoTextField.setEnabled(false);
        tipoCursoTextField.setEnabled(false);
        cancelarCursoButton.setBackground(Color.LIGHT_GRAY);
        cursosComboBoxActionPerformed(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursosTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarCursoButton;
    private javax.swing.JButton atualizarCursoButton;
    private javax.swing.JButton cancelarCursoButton;
    private javax.swing.JComboBox<Curso> cursosComboBox;
    private javax.swing.JTextField idCursoTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeCursoTextField;
    private javax.swing.JButton removerCursoButton;
    private javax.swing.JTextField tipoCursoTextField;
    // End of variables declaration//GEN-END:variables
}
